### ISSUE TITLE
Inventory system

### ISSUE THREAD

**Issue by cmbcoldspot** [Navatusein/Minecraft-GLFW#18]
Нужно сделать систему инвентаря. Ее будем прикручивать не только персонажу, но и сундукам, существам и тд.
Базовая схема: есть класс **Item** (пока пусть хранит id предмета и максимальное количество в стеке). 
Дальше есть структура **InventorySlot**. Она хранит в себе обьект класса Item и количество предмета в стеке.
И есть сам **_класс инвентаря_**. Он как минимум должен иметь массив или любой другой контейнер (list, map, vector...) обьектов класса _InventorySlot_ и максимальное количество предметов/слотов которые может иметь данный инвентарь.

**Comment by Navatusein** [comment]
Vector для хранения предметов будет достаточно.

**Comment by Navatusein** [comment]
То есть создать вектор с размером допустим 36 как количество слотов в обычном одиночном сундуке из майна 
![image](https://user-images.githubusercontent.com/53920406/99575686-a48cbf80-29e1-11eb-83b9-6ce3fc929128.png)

**Comment by Navatusein** [comment]
Использовать чистые массивы не получится так как размер инвентаря может меняться. Динамическое выделение памяти тоже не стоит, вы можете не уследить. Так что `

struct slot {
	item* Item;
	unsigned char Count;
};

std::vector<slot> inventory;
inventory.resizeresize(36);
`

**Comment by Navatusein** [comment]
`с++` вів
