### ISSUE TITLE
Создать класс Shader

### ISSUE THREAD

**Issue by cmbcoldspot** [Navatusein/Minecraft-GLFW#8]

**Comment by cmbcoldspot** [comment]
В целом все вроде хорошо, шейдер парсится, но по какой-то причине не работает.
Возможно нужно переделать компилятор шейдера, либо переписать сам GLSL код (но это маловероятно)

**Comment by Navatusein** [comment]
А что именно с ним не так ?

**Comment by cmbcoldspot** [comment]
> 
> 
> А что именно с ним не так ?

я задал цвет строкой в вертекс шейдере a_color = vec4(0.2f, 0.8f, 0.4f, 1.f);  (a_color по идее передает значение в фрагмент шейдер), но отрисованный квадрат все же был белым.

**Comment by cmbcoldspot** [comment]
Нашел одну из причин бага.
При вызове функции glAttachShader (на любом из обоих шейдеров при любой последовательности) OpenGL выдает ошибку 1282
